### ISSUE TITLE
Twocan should rely on library to parse NMEA2000 messages

### ISSUE THREAD

**Issue by pmarches** [TwoCanPlugIn/TwoCanPlugIn#15]
Twocan should not have the burden of parsing NMEA2000 messages. Rely instead on a library such as https://github.com/ttlappalainen/NMEA2000 .

This will make Twocan compatible with more devices and benefit from other's bugfixes.

Would you merge a PR that goes in this direction?

**Comment by TwoCanPlugIn** [comment]
No.
