### ISSUE TITLE
Building for non-raspberry arm64

### ISSUE THREAD

**Issue by navado** [TwoCanPlugIn/TwoCanPlugIn#16]
I'm trying to build TwoCanPlugin for IMX8PLUS on the target (no cross-compiler toolchain, Embedded Debian 12.5) following instructions in the README.md for linux.
Meanwhile found few issues and one question:
0. (question) is there a reason that build for Raspberry PI is specific for Raspbeerry and not generic ARM64 for linux?
1. Need to install build dependencies that are not listed in `README.md` (the easy part)
```
sudo apt install libbz2-dev libwxgtk3.2-dev gettext
```
2.  It seems that `cmake ..` is not setting `PKG_TARGET` by default
SOLVED. There were no `lsb_release` for this distro

3. After building package, attempt to import `tar.gz` package into OpenCPN fails with **"Error, import plugin tarball does not contain required metadata"**

4. Installing with **deb** package does not have effect.
To make the package installable, need to change and install dependencies `libwxgtk3.2-1, wx3.2-i18n ` because original versions not installable with **Debian 12.5** and **arm64** architecture

4.1. Package installs `libtwocan_plugin_pi.so` to wrong location for the native OpenCPN install. After copying the plugin is discovered, but not configured and not loading in OpenCPN 
```
sudo cp /usr/local/lib/opencpn/libtwocan_plugin_pi.so /usr/lib/opencpn/ -v

```
in OpenCPN logs:
```
20:17:12.085 MESSAGE plugin_loader.cpp:1143 Plugin is compatible by elf library scan: true
20:17:12.086 MESSAGE plugin_loader.cpp:1206 PluginLoader: Loading PlugIn: /usr/lib/opencpn/libgrib_pi.so
20:17:12.096 MESSAGE plugin_loader.cpp:271 Checking plugin candidate: /usr/lib/opencpn/libtwocan_plugin_pi.so
20:17:12.097 MESSAGE plugin_loader.cpp:271 Checking plugin candidate: /usr/lib/opencpn/libchartdldr_pi.so
20:17:14.134 MESSAGE ocpn_frame.cpp:5641 LOGBOOK:  2024-04-10 20:17:14 UTC  DR Lat   37.79540 Lon   26.67880
20:17:16.711 MESSAGE OCPNPlatform.cpp:1006 ChangeLocale: Language load for:  
20:17:16.711 MESSAGE OCPNPlatform.cpp:1047 ChangeLocale: Fall back to en_US
```
```

**Comment by TwoCanPlugIn** [comment]
Refer to my comments on cruisers forum. 

I'd suggest that some of the errors occurred because you have not fully set up your build environment. (missing gettext etc.)

Building the plugins in the CI environment is performed by various shell scripts particular to each platform and the creation of the tarball & metadata are performed by the cloudsmith_upload.sh shell script.

All of this normally gets done in the Circle CI build environment.

I should really delete the "old" build instructions.
